syntax on	"enable syntax highlighting
set number	"show line numbers
set tabstop=4	"tabs show as 4 spaces
set showmatch	"highlight matching []{}()
filetype plugin on
filetype indent off
set hlsearch	"highlight search matches
"binds nohlsearch (removes search highlights) to backspace
nnoremap <backspace> :nohlsearch<CR>
set hidden "allows having multiple open files
set smartcase "smart case in searches
set mouse=a "enable mouse
set autoindent "automatically keep indents
set incsearch "hightlight while searching
"autogenerated by pathogen, turns it on
execute pathogen#infect()
call pathogen#helptags()
