alias mess="/home/rooxo/Games/mame/mess64"
alias reloadXresources="xrdb ~/.Xresources"
alias init="reloadXresources && restartFRITZwifi.sh && exit"
alias update='pacaur -Syu'
PATH=~/Apps/stuff/utils:~/Apps/stuff/cron:$PATH
#TERM=rxvt
#export TERM
EDITOR=vim
export EDITOR
